version: '3.8'
services:
  web:
    image: 0xe14y3/psusphere:latest # Note: 'image' not 'build'
    command: sh -c "python projectsite/manage.py migrate && python projectsite/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - django_data:/app
    environment:
      - DEBUG=1
      - USE_SQLITE=true
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

volumes:
  django_data: